site_name: SaLinA

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_source: true
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.path.append("salina")
          selection:
            new_path_syntax: true
